// Single source of truth for the 8 Basecoat style packs (spec §6).
// Consumed by scripts/build-pack-entries.mjs (emits one CSS entry per pack) and
// vite.config.mjs (one Rollup input per pack). Basecoat forbids combining packs —
// each is a standalone bundle, exactly one enqueued at runtime
// (docs/gotchas/basecoat-style-packs-standalone.md).
export const PACKS = ['vega', 'nova', 'maia', 'lyra', 'mira', 'luma', 'sera', 'rhea'];

// Basecoat's own default pack, and therefore the theme's default when the
// style_preset theme_mod is unset or holds a value not in PACKS.
export const DEFAULT_PACK = 'vega';

// The CSS for one pack's standalone Vite entry. Byte-identical between packs
// except the single `@import 'basecoat-css/<pack>'` line. The import ORDER is
// load-bearing and mirrors the proven app.css structure:
//   tailwind -> pack -> our tokens -> adapter -> states.
// The pack must land AFTER tailwind and BEFORE our tokens: both Basecoat's and
// our tokens are un-layered :root rules, so source order alone decides the
// winner — moving tokens above the pack silently discards every design token
// (docs/gotchas/basecoat-tokens-are-un-layered.md). Paths are relative to the
// generated file's home, src/css/packs/.
export function packEntryCss(pack) {
  if (!PACKS.includes(pack)) {
    throw new Error(`Unknown Basecoat style pack: ${pack}`);
  }
  return `/* GENERATED by scripts/build-pack-entries.mjs — do not edit by hand.
 * Standalone CSS bundle for the Basecoat "${pack}" style pack (spec §6).
 * Import order is the contract; see the generator and
 * docs/gotchas/basecoat-tokens-are-un-layered.md.
 */
@source "../../../woodev-base-theme/**/*.php";

@layer theme, base, components, adapter, utilities;

@import 'tailwindcss';

/* The style pack. Exactly one per bundle — Basecoat forbids combining packs.
 * Only this line differs between the 8 generated entries. */
@import 'basecoat-css/${pack}';

/* MUST follow the pack: un-layered tokens win by source order. */
@import '../tokens.generated.css';

@import '../adapter/index.css' layer(adapter);
@import '../states.css';
`;
}
